Sergio/pokerhands
fjprog101/AT15 pull request #11
Opened 2022-03-09 13:19 UTC by SerJimmy

2022-03-12 06:31 UTC, J0c4 requested changes
Nice job, please check my comments

2022-03-12 06:31 UTC, J0c4 commented on src/test/java/org/fundacionjala/at15/katas/pokerhands/sergio/ThreesomeIdentifierTest.java
> +public class ThreesomeIdentifierTest {
Nice work on the tests

2022-03-13 01:41 UTC, SerJimmy commented on .gitignore
> +.idea
done

2022-03-13 01:44 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/sergio/Croupier.java
> +
they are not empty, I need those ones to make the first comparation

2022-03-13 01:45 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/sergio/Croupier.java
> +public class Croupier {
thanks, decide the winner, but Croupier is in French, I don't know if works

2022-03-13 01:45 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/sergio/Identifier.java
> +    public abstract void theIdentification(List<Card> newPokerHand);
I tried do a refactor, but a lot of code brake if I try it, I'll asume this bug.

2022-03-13 01:46 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/sergio/Main.java
> +public class Main {
done

2022-03-13 01:46 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/sergio/Identifier.java
> +public abstract class Identifier {
thanks, though I couldn't find a way to use interfaces.

2022-03-13 01:47 UTC, SerJimmy commented on src/test/java/org/fundacionjala/at15/katas/pokerhands/sergio/ThreesomeIdentifierTest.java
> +public class ThreesomeIdentifierTest {
thanks, 99% code coverage

2022-03-21 04:23 UTC, J0c4 approved these changes
Great job!

About the empty lines, I actually meant when there are lines without statements that not necessarily helps to code readability, for example, if you have
```
int a = 10
int b = 30


int c = 36
```
You have unneeded empty lines between declaration of variable "b" and "c". If you remove them, it looks like this
```
int a = 10
int b = 30
int c = 36
```

That way, you get a cleaner code.

Your class and method names are very good. Few exceptions where you start method names with "the" is where maybe can be changed to a verb that describes better what is the method doing (example: "calculate", "estimate", etc)

2022-03-22 00:30 UTC, J0c4 approved these changes

2022-03-22 00:30 UTC, merged