Saul/class item
fjprog101/AT15 pull request #38
Opened 2022-03-20 18:07 UTC by eliosfg

2022-03-20 20:47 UTC, SerJimmy requested changes
I think an abstract class shouldn't have constructor, nor test.

2022-03-20 21:21 UTC, eliosfg commented
I refactored according your comment

2022-03-21 01:07 UTC, SerJimmy approved these changes

2022-03-21 01:07 UTC, merged

2022-03-21 13:29 UTC, adhes14 commented on src/main/java/org/fundacionjala/at15/pokemon/Item.java
> +    private int cost;
this must be protected in order to extend other classes