Gonzalo/pokerhands
fjprog101/AT15 pull request #5
Opened 2022-03-09 12:41 UTC by dulphyj

2022-03-12 04:20 UTC, J0c4 requested changes

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/Compare.java
> +    public boolean compareCard1(String[] hand) {
This is good. Try to improve it by avoiding repeating code in `compareCard2`, `compareCard3` and so on. You should be able to have one single method `compareCard` that you could reuse for all cards

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/Compare.java
> +    public boolean isStraight(String[] hand) {
cool that you are using boolean!

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/Cards.java
> +    public abstract List<String> cards(String suit);
Always try to use a verb for method names, this way it helps to describe what the method is doing (in this case, does it get cards? does it read cards? does it create cards?)

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/Compare.java
> +    public boolean compareCard3(String[] hand) {
by the return type, looks like the name of this method should be improved. Yes, it compares two cards, but what is comparing? and what does the result mean? for what I read in the code, I assume this chould be `doesCardsHaveTheSameValue(...)` or `isHandAStraight(...)`

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/Converter.java
> +public class Converter {
Good name

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/Converter.java
> +    public char[] converterCharValue(String[] hand) {
Good name, I would improve it to `convertValuesToChar()`. Same for suit and int

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/DeckOfCards.java
> +    private Cards suit;
Nice

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/ValueHandFlush.java
> +    private String isFlush;
Looks like this should be a boolean

2022-03-12 04:20 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/pokerhands/gonzalo/ValueHandStraightFlush.java
> +    private String isFlush;
boolean?

2022-03-12 04:20 UTC, J0c4 commented on src/test/java/org/fundacionjala/at15/katas/pokerHands/gonzalo/CompareTest.java
> +
Please remove empty lines that do not help to improve code readability

2022-03-12 04:20 UTC, J0c4 commented on src/test/java/org/fundacionjala/at15/katas/pokerHands/gonzalo/CompareTest.java
> +        assertEquals(expected, compare.isStraight(hand));
you could use `assertTrue` instead in order to simplify

2022-03-12 04:20 UTC, J0c4 commented on src/test/java/org/fundacionjala/at15/katas/pokerHands/gonzalo/CompareTest.java
> +
unnecessary empty lines

2022-03-12 04:20 UTC, J0c4 commented on src/test/java/org/fundacionjala/at15/katas/pokerHands/gonzalo/ValueHandStraightTest.java
> +public class ValueHandStraightTest {
Nice tests

2022-03-15 03:31 UTC, dulphyj commented
I'm not sure about the last two classes added, DealCards and Main, I don't know how to test when I use random numbers, in theory it already works, I just can't check between hands with the same game which one is worth more Eg "AS AH AC 2S 3H " And "7S 7H 7C KS AC" should win the first hand, but my result is "equal"

2022-03-21 03:57 UTC, J0c4 commented
The way the logic is separated it helps to have smaller pieces that are easier to review and understand and in general you did a good job identifying possible classes with specific responsability

What it needs to be improved is how you define your classes (specially the names) so when you create an object from the classes, they make sense when you read their state and behavior. For example, you have 
```
CardSuit cardSuit = new CardSuit()
cardSuit.cards(...)
```
Which would be read as "an object cardSuit do cards". Instead, if method name is improved, you could have something like
```
CardSuit cardSuit = new CardSuit()
cardSuit.createCards(...)
```
Then, it can be read as "an object cardSuit creates cards", which reflects the name and what is that object doing when you call that specific method.

2022-03-21 03:57 UTC, J0c4 approved these changes

2022-03-21 03:57 UTC, merged